export const renderINITscreen = {
  "DOM": "<div>Loading user application data...</div>"
};
export const renderAboutInitScreen = {
  "DOM": '<div id=\"page\"><div class=\"ui icon message\"><i class=\"inbox icon\"></i><div class=\"content\"><div class=\"header\">Beyond and further</div><p>1984.09.09</p></div></div><div class=\"ui description\"><p>Complete your application for Beyond and further</p></div><div class=\"ui steps\"><a class=\"active step\"><div class=\"content\">About</div></a><a class=\"step\"><div class=\"content\">Question</div></a><a class=\"step\"><div class=\"content\">Teams</div></a><a class=\"step\"><div class=\"content\">Review</div></a></div><div class=\"ui bottom attached segment\"><form class=\"ui form\"><h4 class=\"ui dividing header\">About you</h4><div class=\"field\"><input class=\"c-textfield__input--super-power\" type=\"text\" name=\"userapp[superpower]\" placeholder=\"What is your superpower?\" required=\"false\"><div class=\"c-textfield__error c-textfield__error--super-power\"></div></div><h4 class=\"ui dividing header\">Personal details</h4><div class=\"field\"><input class=\"c-textfield__input--legal-name\" type=\"text\" name=\"userapp[legal-name]\" placeholder=\"Legal name\" required=\"false\"><div class=\"c-textfield__error c-textfield__error--legal-name\"></div></div><div class=\"field\"><input class=\"c-textfield__input--preferred-name\" type=\"text\" name=\"userapp[preferred-name]\" placeholder=\"Preferred name\" required=\"false\"><div class=\"c-textfield__error c-textfield__error--preferred-name\"></div></div><div class=\"field\"><input class=\"c-textfield__input--phone\" type=\"text\" name=\"userapp[phone]\" placeholder=\"Phone\" required=\"false\"><div class=\"c-textfield__error c-textfield__error--phone\"></div></div><div class=\"two fields\"><div class=\"field\"><input class=\"c-textfield__input--birthday\" type=\"text\" name=\"userapp[birthday]\" placeholder=\"Birthday\" required=\"false\"><div class=\"c-textfield__error c-textfield__error--birthday\"></div></div><div class=\"field\"><input class=\"c-textfield__input--zip-code\" type=\"text\" name=\"userapp[zip-code]\" placeholder=\"Zip code\" required=\"false\"><div class=\"c-textfield__error c-textfield__error--zip-code\"></div></div></div></form></div><div class=\"c-btn c-btn--primary c-application__submit-about ui fluid primary button\" tabindex=\"0\">Continue</div><div class=\"c-application__error\"></div></div>'
};
export const renderAboutScreen = (obj) => ({
  "DOM": `<div id=\"page\"><div class=\"ui icon message\"><i class=\"inbox icon\"></i><div class=\"content\"><div class=\"header\">Beyond and further</div><p>1984.09.09</p></div></div><div class=\"ui description\"><p>Complete your application for Beyond and further</p></div><div class=\"ui steps\"><a class=\"active step\"><div class=\"content\">About</div></a><a class=\"step\"><div class=\"content\">Question</div></a><a class=\"step\"><div class=\"content\">Teams</div></a><a class=\"step\"><div class=\"content\">Review</div></a></div><div class=\"ui bottom attached segment\"><form class=\"ui form\"><h4 class=\"ui dividing header\">About you</h4><div class=\"field\"><input class=\"c-textfield__input--super-power\" type=\"text\" name=\"userapp[superpower]\" placeholder=\"What is your superpower?\" ${'superPower' in obj ? 'value="' + obj.superPower + '" ' : ''}required=\"false\"><div class=\"c-textfield__error c-textfield__error--super-power\"></div></div><h4 class=\"ui dividing header\">Personal details</h4><div class=\"field\"><input class=\"c-textfield__input--legal-name\" type=\"text\" name=\"userapp[legal-name]\" placeholder=\"Legal name\" ${'legalName' in obj ? 'value="' + obj.legalName + '" ' : ''}required=\"false\"><div class=\"c-textfield__error c-textfield__error--legal-name\"></div></div><div class=\"field\"><input class=\"c-textfield__input--preferred-name\" type=\"text\" name=\"userapp[preferred-name]\" placeholder=\"Preferred name\" ${'preferredName' in obj ? 'value="' + obj.preferredName + '" ' : ''}required=\"false\"><div class=\"c-textfield__error c-textfield__error--preferred-name\"></div></div><div class=\"field\"><input class=\"c-textfield__input--phone\" type=\"text\" name=\"userapp[phone]\" placeholder=\"Phone\" ${'phone' in obj ? 'value="' + obj.phone + '" ' : ''}required=\"false\"><div class=\"c-textfield__error c-textfield__error--phone\"></div></div><div class=\"two fields\"><div class=\"field\"><input class=\"c-textfield__input--birthday\" type=\"text\" name=\"userapp[birthday]\" placeholder=\"Birthday\" ${'birthday' in obj ? 'value="' + obj.birthday + '" ' : ''}required=\"false\"><div class=\"c-textfield__error c-textfield__error--birthday\"></div></div><div class=\"field\"><input class=\"c-textfield__input--zip-code\" type=\"text\" name=\"userapp[zip-code]\" placeholder=\"Zip code\" ${'zipCode' in obj ? 'value="' + obj.zipCode + '" ' : ''}required=\"false\"><div class=\"c-textfield__error c-textfield__error--zip-code\"></div></div></div></form></div><div class=\"c-btn c-btn--primary c-application__submit-about ui fluid primary button\" tabindex=\"0\">Continue</div><div class=\"c-application__error\"></div></div>`
});
export const renderAboutErrorScreen = {
  "DOM": `<div id=\"page\"><div class=\"ui icon message\"><i class=\"inbox icon\"></i><div class=\"content\"><div class=\"header\">Beyond and further</div><p>1984.09.09</p></div></div><div class=\"ui description\"><p>Complete your application for Beyond and further</p></div><div class=\"ui steps\"><a class=\"active step\"><div class=\"content\">About</div></a><a class=\"step\"><div class=\"content\">Question</div></a><a class=\"step\"><div class=\"content\">Teams</div></a><a class=\"step\"><div class=\"content\">Review</div></a></div><div class=\"ui bottom attached segment\"><form class=\"ui form\"><h4 class=\"ui dividing header\">About you</h4><div class=\"field\"><input class=\"c-textfield__input--super-power\" type=\"text\" name=\"userapp[superpower]\" placeholder=\"What is your superpower?\" required=\"false\"><div class=\"c-textfield__error c-textfield__error--super-power\">Mandatory field : please fill in !</div></div><h4 class=\"ui dividing header\">Personal details</h4><div class=\"field\"><input class=\"c-textfield__input--legal-name\" type=\"text\" name=\"userapp[legal-name]\" placeholder=\"Legal name\" required=\"false\"><div class=\"c-textfield__error c-textfield__error--legal-name\">Mandatory field : please fill in !</div></div><div class=\"field\"><input class=\"c-textfield__input--preferred-name\" type=\"text\" name=\"userapp[preferred-name]\" placeholder=\"Preferred name\" required=\"false\"><div class=\"c-textfield__error c-textfield__error--preferred-name\">Mandatory field : please fill in !</div></div><div class=\"field\"><input class=\"c-textfield__input--phone\" type=\"text\" name=\"userapp[phone]\" placeholder=\"Phone\" required=\"false\"><div class=\"c-textfield__error c-textfield__error--phone\">Please fill field with at least 2 characters!</div></div><div class=\"two fields\"><div class=\"field\"><input class=\"c-textfield__input--birthday\" type=\"text\" name=\"userapp[birthday]\" placeholder=\"Birthday\" required=\"false\"><div class=\"c-textfield__error c-textfield__error--birthday\">Please fill field with at least 2 characters!</div></div><div class=\"field\"><input class=\"c-textfield__input--zip-code\" type=\"text\" name=\"userapp[zip-code]\" placeholder=\"Zip code\" required=\"false\"><div class=\"c-textfield__error c-textfield__error--zip-code\">Please fill field with at least 2 characters!</div></div></div></form></div><div class=\"c-btn c-btn--primary c-application__submit-about ui fluid primary button\" tabindex=\"0\">Continue</div><div class=\"c-application__error\"></div></div>`
}
export const renderTeamScreen = ([isTeam0Joined, isTeam1Joined]) => ({
  "DOM": `<div id=\"page\"><div class=\"ui icon message\"><i class=\"inbox icon\"></i><div class=\"content\"><div class=\"header\">Beyond and further</div><p>1984.09.09</p></div></div><div class=\"ui description\"><p>Complete your application for Beyond and further</p></div><div class=\"ui steps\"><a class=\"step\"><div class=\"content\">About</div></a><a class=\"step\"><div class=\"content\">Question</div></a><a class=\"active step\"><div class=\"content\">Teams</div></a><a class=\"step\"><div class=\"content\">Review</div></a></div><div class=\"ui bottom attached segment\"><h4 class=\"ui dividing header\">Select a team</h4><div class=\"c-application__teams-list ui list\"><div class=\"item\"><div class=\"right floated content\"><div class=\"ui button\">${isTeam0Joined ? 'O' : 'X'}</div></div><img class=\"ui avatar image\" src=\"./assets/images/teams/Parking.jpg\"><div class=\"content\" data-index=\"0\">Parking</div></div><div class=\"item\"><div class=\"right floated content\"><div class=\"ui button\">${isTeam1Joined ? 'O' : 'X'}</div></div><img class=\"ui avatar image\" src=\"./assets/images/teams/Box Office.jpg\"><div class=\"content\" data-index=\"1\">Box Office</div></div></div></div><div class=\"c-btn c-btn--primary c-application__submit--continue ${!isTeam0Joined && !isTeam1Joined ? 'disabled ' : ''}ui fluid primary button\" tabindex=\"0\">Continue</div><div class=\"c-application__error\"></div></div>`
});
export const renderTeamDetailJoinScreen = answer => ([
  {
    DOM: `<div id=\"page\"><div class=\"ui icon message\"><i class=\"inbox icon\"></i><div class=\"content\"><div class=\"header\">Beyond and further</div><p>1984.09.09</p></div></div><div class=\"ui description\"><p>Complete your application for Beyond and further</p></div><div class=\"ui steps\"><a class=\"step\"><div class=\"content\">About</div></a><a class=\"step\"><div class=\"content\">Question</div></a><a class=\"active step\"><div class=\"content\">Teams</div></a><a class=\"step\"><div class=\"content\">Review</div></a></div><div class=\"ui bottom attached segment\"><div class=\"c-application__team_detail-back ui fluid negative button\" tabindex=\"0\">Back to teams</div><div class=\"ui divided selection list\"><a class=\"item\"><div class=\"ui horizontal label\">Parking</div>Be one of the first faces people see and direct them their parking spot. Enjoy the many perks of this highly social position. </a></div><form class=\"ui form\"><div class=\"ui icon message\"><i class=\"inbox icon\"></i><div class=\"content\"><div class=\"header\">Have you worked parking for any other festivals? Which ones?</div><p>Team lead&#39;s name/role</p></div></div><div class=\"field\"><textarea class=\"c-textfield__input--team_detail_answer\" name=\"userapp[organizer-question]\" placeholder=\"Please enter your answer here\" required=\"false\">${answer ? answer : ''}</textarea><div class=\"c-textfield__error c-textfield__error--td\"></div></div></form></div><div class=\"ui fluid buttons\"><button class=\"c-btn c-btn--quiet c-application__submit--team_detail_skip ui button\">Skip this team</button><div class=\"or\"></div><button class=\"c-application__submit--team_detail_join ui positive button\">Join team</button></div><div class=\"c-application__error\"></div></div>`
  },
  {
    DOM: `<div id=\"page\"><div class=\"ui icon message\"><i class=\"inbox icon\"></i><div class=\"content\"><div class=\"header\">Beyond and further</div><p>1984.09.09</p></div></div><div class=\"ui description\"><p>Complete your application for Beyond and further</p></div><div class=\"ui steps\"><a class=\"step\"><div class=\"content\">About</div></a><a class=\"step\"><div class=\"content\">Question</div></a><a class=\"active step\"><div class=\"content\">Teams</div></a><a class=\"step\"><div class=\"content\">Review</div></a></div><div class=\"ui bottom attached segment\"><div class=\"c-application__team_detail-back ui fluid negative button\" tabindex=\"0\">Back to teams</div><div class=\"ui divided selection list\"><a class=\"item\"><div class=\"ui horizontal label\">Box Office</div>The gateway to Cosmic Alignment! Here, you&#39;ll be selling GA tickets, banding guests and checking in artists. This job requires organization and a friendly face.</a></div><form class=\"ui form\"><div class=\"ui icon message\"><i class=\"inbox icon\"></i><div class=\"content\"><div class=\"header\">Which festivals have you worked Box Office before?</div><p>Team lead&#39;s name/role</p></div></div><div class=\"field\"><textarea class=\"c-textfield__input--team_detail_answer\" name=\"userapp[organizer-question]\" placeholder=\"Please enter your answer here\" required=\"false\">${answer ? answer : ''}</textarea><div class=\"c-textfield__error c-textfield__error--td\"></div></div></form></div><div class=\"ui fluid buttons\"><button class=\"c-btn c-btn--quiet c-application__submit--team_detail_skip ui button\">Skip this team</button><div class=\"or\"></div><button class=\"c-application__submit--team_detail_join ui positive button\">Join team</button></div><div class=\"c-application__error\"></div></div>`
  }
]);
export const renderTeamDetailUnjoinScreen = answer => ([
  {
    DOM: `<div id=\"page\"><div class=\"ui icon message\"><i class=\"inbox icon\"></i><div class=\"content\"><div class=\"header\">Beyond and further</div><p>1984.09.09</p></div></div><div class=\"ui description\"><p>Complete your application for Beyond and further</p></div><div class=\"ui steps\"><a class=\"step\"><div class=\"content\">About</div></a><a class=\"step\"><div class=\"content\">Question</div></a><a class=\"active step\"><div class=\"content\">Teams</div></a><a class=\"step\"><div class=\"content\">Review</div></a></div><div class=\"ui bottom attached segment\"><div class=\"c-application__team_detail-back ui fluid negative button\" tabindex=\"0\">Back to teams</div><div class=\"ui divided selection list\"><a class=\"item\"><div class=\"ui horizontal label\">Parking</div>Be one of the first faces people see and direct them their parking spot. Enjoy the many perks of this highly social position. </a></div><form class=\"ui form\"><div class=\"ui icon message\"><i class=\"inbox icon\"></i><div class=\"content\"><div class=\"header\">Have you worked parking for any other festivals? Which ones?</div><p>Team lead&#39;s name/role</p></div></div><div class=\"field\"><textarea class=\"c-textfield__input--team_detail_answer\" name=\"userapp[organizer-question]\" placeholder=\"Please enter your answer here\" required=\"false\">${answer ? answer : ''}</textarea><div class=\"c-textfield__error c-textfield__error--td\"></div></div></form></div><div class=\"ui fluid buttons\"><button class=\"c-btn c-btn--quiet c-application__submit--team_detail_skip ui button\">Skip this team</button><div class=\"or\"></div><button class=\"c-application__submit--team_detail_join ui positive button\">Unjoin team</button></div><div class=\"c-application__error\"></div></div>`
  },
  {
    DOM: `<div id=\"page\"><div class=\"ui icon message\"><i class=\"inbox icon\"></i><div class=\"content\"><div class=\"header\">Beyond and further</div><p>1984.09.09</p></div></div><div class=\"ui description\"><p>Complete your application for Beyond and further</p></div><div class=\"ui steps\"><a class=\"step\"><div class=\"content\">About</div></a><a class=\"step\"><div class=\"content\">Question</div></a><a class=\"active step\"><div class=\"content\">Teams</div></a><a class=\"step\"><div class=\"content\">Review</div></a></div><div class=\"ui bottom attached segment\"><div class=\"c-application__team_detail-back ui fluid negative button\" tabindex=\"0\">Back to teams</div><div class=\"ui divided selection list\"><a class=\"item\"><div class=\"ui horizontal label\">Box Office</div>The gateway to Cosmic Alignment! Here, you&#39;ll be selling GA tickets, banding guests and checking in artists. This job requires organization and a friendly face.</a></div><form class=\"ui form\"><div class=\"ui icon message\"><i class=\"inbox icon\"></i><div class=\"content\"><div class=\"header\">Which festivals have you worked Box Office before?</div><p>Team lead&#39;s name/role</p></div></div><div class=\"field\"><textarea class=\"c-textfield__input--team_detail_answer\" name=\"userapp[organizer-question]\" placeholder=\"Please enter your answer here\" required=\"false\">${answer ? answer : ''}</textarea><div class=\"c-textfield__error c-textfield__error--td\"></div></div></form></div><div class=\"ui fluid buttons\"><button class=\"c-btn c-btn--quiet c-application__submit--team_detail_skip ui button\">Skip this team</button><div class=\"or\"></div><button class=\"c-application__submit--team_detail_join ui positive button\">Unjoin team</button></div><div class=\"c-application__error\"></div></div>`
  }
]);
export const renderTeamDetailBackToUnjoinScreen = answer => ([
  {
    DOM: `<div id=\"page\"><div class=\"ui icon message\"><i class=\"inbox icon\"></i><div class=\"content\"><div class=\"header\">Beyond and further</div><p>1984.09.09</p></div></div><div class=\"ui description\"><p>Complete your application for Beyond and further</p></div><div class=\"ui steps\"><a class=\"step\"><div class=\"content\">About</div></a><a class=\"step\"><div class=\"content\">Question</div></a><a class=\"active step\"><div class=\"content\">Teams</div></a><a class=\"step\"><div class=\"content\">Review</div></a></div><div class=\"ui bottom attached segment\"><div class=\"c-application__team_detail-back ui fluid negative button\" tabindex=\"0\">Back to teams</div><div class=\"ui divided selection list\"><a class=\"item\"><div class=\"ui horizontal label\">Parking</div>Be one of the first faces people see and direct them their parking spot. Enjoy the many perks of this highly social position. </a></div><form class=\"ui form\"><div class=\"ui icon message\"><i class=\"inbox icon\"></i><div class=\"content\"><div class=\"header\">Have you worked parking for any other festivals? Which ones?</div><p>Team lead&#39;s name/role</p></div></div><div class=\"field\"><textarea class=\"c-textfield__input--team_detail_answer\" name=\"userapp[organizer-question]\" placeholder=\"Please enter your answer here\"${answer ? ' value="' + answer + '"' : ''} required=\"false\"></textarea><div class=\"c-textfield__error c-textfield__error--td\"></div></div></form></div><div class=\"ui fluid buttons\"><button class=\"c-btn c-btn--quiet c-application__submit--team_detail_skip ui button\">Skip this team</button><div class=\"or\"></div><button class=\"c-application__submit--team_detail_join ui positive button\">Unjoin team</button></div><div class=\"c-application__error\"></div></div>`
  },
  {
    DOM: `<div id=\"page\"><div class=\"ui icon message\"><i class=\"inbox icon\"></i><div class=\"content\"><div class=\"header\">Beyond and further</div><p>1984.09.09</p></div></div><div class=\"ui description\"><p>Complete your application for Beyond and further</p></div><div class=\"ui steps\"><a class=\"step\"><div class=\"content\">About</div></a><a class=\"step\"><div class=\"content\">Question</div></a><a class=\"active step\"><div class=\"content\">Teams</div></a><a class=\"step\"><div class=\"content\">Review</div></a></div><div class=\"ui bottom attached segment\"><div class=\"c-application__team_detail-back ui fluid negative button\" tabindex=\"0\">Back to teams</div><div class=\"ui divided selection list\"><a class=\"item\"><div class=\"ui horizontal label\">Box Office</div>The gateway to Cosmic Alignment! Here, you&#39;ll be selling GA tickets, banding guests and checking in artists. This job requires organization and a friendly face.</a></div><form class=\"ui form\"><div class=\"ui icon message\"><i class=\"inbox icon\"></i><div class=\"content\"><div class=\"header\">Which festivals have you worked Box Office before?</div><p>Team lead&#39;s name/role</p></div></div><div class=\"field\"><textarea class=\"c-textfield__input--team_detail_answer\" name=\"userapp[organizer-question]\" placeholder=\"Please enter your answer here\" required=\"false\">${answer ? answer : ''}</textarea><div class=\"c-textfield__error c-textfield__error--td\"></div></div></form></div><div class=\"ui fluid buttons\"><button class=\"c-btn c-btn--quiet c-application__submit--team_detail_skip ui button\">Skip this team</button><div class=\"or\"></div><button class=\"c-application__submit--team_detail_join ui positive button\">Unjoin team</button></div><div class=\"c-application__error\"></div></div>`
  }
]);
export const renderInvalidTeamDetailJoinScreen = answer => ([
  {
    DOM: `<div id=\"page\"><div class=\"ui icon message\"><i class=\"inbox icon\"></i><div class=\"content\"><div class=\"header\">Beyond and further</div><p>1984.09.09</p></div></div><div class=\"ui description\"><p>Complete your application for Beyond and further</p></div><div class=\"ui steps\"><a class=\"step\"><div class=\"content\">About</div></a><a class=\"step\"><div class=\"content\">Question</div></a><a class=\"active step\"><div class=\"content\">Teams</div></a><a class=\"step\"><div class=\"content\">Review</div></a></div><div class=\"ui bottom attached segment\"><div class=\"c-application__team_detail-back ui fluid negative button\" tabindex=\"0\">Back to teams</div><div class=\"ui divided selection list\"><a class=\"item\"><div class=\"ui horizontal label\">Parking</div>Be one of the first faces people see and direct them their parking spot. Enjoy the many perks of this highly social position. </a></div><form class=\"ui form\"><div class=\"ui icon message\"><i class=\"inbox icon\"></i><div class=\"content\"><div class=\"header\">Have you worked parking for any other festivals? Which ones?</div><p>Team lead&#39;s name/role</p></div></div><div class=\"field\"><textarea class=\"c-textfield__input--team_detail_answer\" name=\"userapp[organizer-question]\" placeholder=\"Please enter your answer here\" required=\"false\"></textarea><div class=\"c-textfield__error c-textfield__error--td\">Mandatory field : please fill in !</div></div></form></div><div class=\"ui fluid buttons\"><button class=\"c-btn c-btn--quiet c-application__submit--team_detail_skip ui button\">Skip this team</button><div class=\"or\"></div><button class=\"c-application__submit--team_detail_join ui positive button\">Join team</button></div><div class=\"c-application__error\"></div></div>`
  },
  {} // TODO
]);
export const renderInvalidTeamDetailUnjoinScreen = answer => ([
  {
    DOM: `<div id=\"page\"><div class=\"ui icon message\"><i class=\"inbox icon\"></i><div class=\"content\"><div class=\"header\">Beyond and further</div><p>1984.09.09</p></div></div><div class=\"ui description\"><p>Complete your application for Beyond and further</p></div><div class=\"ui steps\"><a class=\"step\"><div class=\"content\">About</div></a><a class=\"step\"><div class=\"content\">Question</div></a><a class=\"active step\"><div class=\"content\">Teams</div></a><a class=\"step\"><div class=\"content\">Review</div></a></div><div class=\"ui bottom attached segment\"><div class=\"c-application__team_detail-back ui fluid negative button\" tabindex=\"0\">Back to teams</div><div class=\"ui divided selection list\"><a class=\"item\"><div class=\"ui horizontal label\">Parking</div>Be one of the first faces people see and direct them their parking spot. Enjoy the many perks of this highly social position. </a></div><form class=\"ui form\"><div class=\"ui icon message\"><i class=\"inbox icon\"></i><div class=\"content\"><div class=\"header\">Have you worked parking for any other festivals? Which ones?</div><p>Team lead&#39;s name/role</p></div></div><div class=\"field\"><textarea class=\"c-textfield__input--team_detail_answer\" name=\"userapp[organizer-question]\" placeholder=\"Please enter your answer here\" required=\"false\"></textarea><div class=\"c-textfield__error c-textfield__error--td\">Mandatory field : please fill in !</div></div></form></div><div class=\"ui fluid buttons\"><button class=\"c-btn c-btn--quiet c-application__submit--team_detail_skip ui button\">Skip this team</button><div class=\"or\"></div><button class=\"c-application__submit--team_detail_join ui positive button\">Unjoin team</button></div><div class=\"c-application__error\"></div></div>`
  },
  {} // TODO
]);
export const renderReviewScreen = ({ hasBeenJoined, superPower, question }) => ({
  "DOM": `<div id=\"page\"><div class=\"ui icon message\"><i class=\"inbox icon\"></i><div class=\"content\"><div class=\"header\">Beyond and further</div><p>1984.09.09</p></div></div><div class=\"ui description\"><p>Does this look good ?</p></div><div class=\"ui steps\"><a class=\"step\"><div class=\"content\">About</div></a><a class=\"step\"><div class=\"content\">Question</div></a><a class=\"step\"><div class=\"content\">Teams</div></a><a class=\"active step\"><div class=\"content\">Review</div></a></div><div class=\"ui one cards\"><div class=\"card\"><div class=\"content\"><i class=\"c-application__change--about right floated edit icon\"></i><div class=\"header\">About you</div><div class=\"ui list\"><div class=\"item\"><div class=\"ui button\"><i class=\"info icon\"></i></div>${superPower ? superPower : 'fly'}</div><div class=\"item\"><div class=\"ui button\"><i class=\"user outline icon\"></i></div>Kujio (Otadaki)</div><div class=\"item\"><div class=\"ui button\"><i class=\"text telephone icon\"></i></div>1234</div><div class=\"item\"><div class=\"ui button\"><i class=\"birthday icon\"></i></div>1984.09.09</div><div class=\"item\"><div class=\"ui button\"><i class=\"info icon\"></i></div>1231</div></div></div></div></div><div class=\"ui one cards\"><div class=\"card\"><div class=\"content\"><i class=\"c-application__change--question right floated edit icon\"></i><div class=\"header\">Organizer&#39;s question</div><div class=\"ui list message\"><div class=\"item\"><img class=\"ui avatar image\" src=\"./assets/images/avatar/small/matt.jpg\" className=\"ui avatar image\"><div class=\"content\"><div class=\"header\">would you catch it?</div>Organizer name and role</div></div></div><div class=\"description\"><img class=\"ui floated right avatar image\" src=\"./assets/images/avatar/large/elliot.jpg\" className=\"ui floated right avatar image\"><p>${question ? question : 'That is what I like'}</p></div></div></div></div><div class=\"ui one cards\"><div class=\"card\"><div class=\"content\"><i class=\"c-application__change--teams right floated edit icon\"></i><div class=\"header\">Team selection</div><div class=\"ui list\">${hasBeenJoined[0] ? '<div class=\"item\"><div class=\"ui button\"><i class=\"info icon\"></i></div>Parking</div>' : ''}${hasBeenJoined[1] ? '<div class="item"><div class="ui button"><i class="info icon"></i></div>Box Office</div>' : ''}</div></div></div></div><div class=\"ui basic segment\"><button class=\"c-application__review--submit ui fluid primary button\">Apply for the things</button></div><div class=\"c-application__error\"></div></div>`
});
export const renderAppliedScreen = {
  "DOM": "<div class=\"ui raised segment\"><p>You successfully applied! Stay in touch</p></div>",
};
export const renderQuestionScreen = (obj) => ({
  "DOM": `<div id=\"page\"><div class=\"ui icon message\"><i class=\"inbox icon\"></i><div class=\"content\"><div class=\"header\">Beyond and further</div><p>1984.09.09</p></div></div><div class=\"ui description\"><p>Complete your application for Beyond and further</p></div><div class=\"ui steps\"><a class=\"step\"><div class=\"content\">About</div></a><a class=\"active step\"><div class=\"content\">Question</div></a><a class=\"step\"><div class=\"content\">Teams</div></a><a class=\"step\"><div class=\"content\">Review</div></a></div><div class=\"ui bottom attached segment\"><form class=\"ui form\"><h4 class=\"ui dividing header\">Organizer&#39;s question</h4><div class=\"ui icon message\"><i class=\"inbox icon\"></i><div class=\"content\"><div class=\"header\">would you catch it?</div><p>Organizer&#39;s name/role</p></div></div><div class=\"field\"><textarea class=\"c-textfield__input--answer\" name=\"userapp[organizer-question]\" placeholder=\"Please enter your answer here\"${'answer' in obj ? ' value="' + obj.answer + '"' : ''} required=\"false\"></textarea><div class=\"c-textfield__error c-textfield__error--answer\"></div></div></form></div><div class=\"c-btn c-btn--primary c-application__submit--question ui fluid primary button\" tabindex=\"0\">Continue</div><div class=\"c-application__error\"></div></div>`
});
export const renderQuestionErrorScreen = ({ answer }) => ({
  "DOM": `<div id=\"page\"><div class=\"ui icon message\"><i class=\"inbox icon\"></i><div class=\"content\"><div class=\"header\">Beyond and further</div><p>1984.09.09</p></div></div><div class=\"ui description\"><p>Complete your application for Beyond and further</p></div><div class=\"ui steps\"><a class=\"step\"><div class=\"content\">About</div></a><a class=\"active step\"><div class=\"content\">Question</div></a><a class=\"step\"><div class=\"content\">Teams</div></a><a class=\"step\"><div class=\"content\">Review</div></a></div><div class=\"ui bottom attached segment\"><form class=\"ui form\"><h4 class=\"ui dividing header\">Organizer&#39;s question</h4><div class=\"ui icon message\"><i class=\"inbox icon\"></i><div class=\"content\"><div class=\"header\">would you catch it?</div><p>Organizer&#39;s name/role</p></div></div><div class=\"field\"><textarea class=\"c-textfield__input--answer\" name=\"userapp[organizer-question]\" placeholder=\"Please enter your answer here\" required=\"false\"></textarea><div class=\"c-textfield__error c-textfield__error--answer\">Mandatory field : please fill in !</div></div></form></div><div class=\"c-btn c-btn--primary c-application__submit--question ui fluid primary button\" tabindex=\"0\">Continue</div><div class=\"c-application__error\"></div></div>`
})
